[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
auction = "HBA191fKk9gWLk3TkVZoUMYnUuhhpiAdXkL43tXY5EJ8"

[programs.devnet]
auction = "HBA191fKk9gWLk3TkVZoUMYnUuhhpiAdXkL43tXY5EJ8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/wallet/test1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
