[features]
resolution = true
skip-lint = false


[workspace]
members = ["./"]


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/wallet/test1.json"

[programs.localnet]
counter = "77tWhvBTKvZVHudKKLV9EpzwFoTrGAJL9gwuNUA9MaRY"

[programs.devnet]
counter = "77tWhvBTKvZVHudKKLV9EpzwFoTrGAJL9gwuNUA9MaRY"

[programs.mainnet]
name-auctioning = "77tWhvBTKvZVHudKKLV9EpzwFoTrGAJL9gwuNUA9MaRY"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"